- SwiftCBOR/CBORDecoder.swift
When trying to decode a UUID string (format "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX") I encountered a crash.
Code:
```swift
// 78 24 61 66 31 63 35 36 37 38 2D 31 33 38 38 2D 34 61 66 61 2D 34 61 64 34 2D 30 35 32 34 39 65 36 65 32 39 37 30
let data: [UInt8] = [0x78, 0x24, 0x61, 0x66, 0x31, 0x63, 0x35, 0x36, 0x37, 0x38, 0x2D, 0x31, 0x33, 0x38, 0x38, 0x2D, 0x34, 0x61, 0x66, 0x61, 0x2D, 0x34, 0x61, 0x64, 0x34, 0x2D, 0x30, 0x35, 0x32, 0x34, 0x39, 0x65, 0x36, 0x65, 0x32, 0x39, 0x37, 0x30]
do {
let cbor = try CBOR.decode(data)
} catch {
}
```
Crash:
```
Simultaneous accesses to 0x174078890, but modification requires exclusive access.
Previous access (a modification) started at sc-test`CBORDecoder.decodeItem() + 10808 (0x1000a5958).
Current access (a modification) started at:
0 …
```
> Simul access fix

- SwiftCBOR/CBORDecoder.swift
Swift 4 raises the error: "'decode' is inaccessible due to 'internal' protection level"
when trying to build the example:
let decoded = try! CBOR.decode([0x9f, ...])
print(decoded)
> Fix protection level

- SwiftCBOR/CBOREncoder.swift
The memory of `[x]` seems to be released before the closure is invoked.
The easiest mitigation is to assign the array to a local variable first `let array = [x]` and then use it - in that case it seems to survive until it goes out of scope at the end of the function.
I took the liberty to simplify the code a bit.
> Prevent use after free in `rawBytes`

- SwiftCBOR/CBOR.swift
- SwiftCBOR/CBORDecoder.swift
- SwiftCBOR/CBOREncodable.swift
- SwiftCBOR/CBOREncoder.swift
- SwiftCBORTests/CBORDecoderTests.swift
- SwiftCBORTests/CBOREncoderTests.swift
Hi Greg,
I started out to support larger tags but somehow got lured into a refactoring spree.
- Support for tags larger than 255 (and add an extensible struct with known values from the spec).
- Default to UInt64 instead of platform-specific width.
- Extracted `readBinaryNumber` to reduce the large decoder `switch`.
- Extracted `encodeVarUInt`.
- Added error that is thrown if sequence is too large for platform (i.e. larger than `Int`).
Let me know if you think I should break this down more.
Cheers,
Marcel
> Default to UInt64 in more places

- Sources/SwiftCBOR/CBORDecoder.swift
CBORDecoder would fail parsing the map `0xbf, 0xff`
> Handle decoding empty, indefinite-length maps

- Sources/SwiftCBOR/CBOR.swift
Made all the known tags, public.
Added new tag 37 for binary encoded UUIDs, as per https://github.com/lucas-clemente/cbor-specs/blob/master/uuid.md
> Made all the known CBOR.Tag static public, add new uuid Tag

- Sources/SwiftCBOR/CBOR.swift
Since the switch statement is not exhaustive, Xcode 11 stops the building process with this error message `The compiler is unable to check that this switch is exhaustive in reasonable time`. By making it exhaustive, the frameworks builds with Xcode 11 and Swift 5 like a charm even using the Package Manager within Xcode 11.
> Ensure compatibility with Xcode 11

- Sources/SwiftCBOR/CBOREncoder.swift
When encoding an Any the check for Bool was highest precedence which meant that if you were working with Objective-C and you had an integer value of 0 or 1 that you wanted to encode as a numeric value then it would be encoded as a Bool. This lowers the precedence of checking for a Bool to be lower than the numeric checks.
> Lower Bool encoding precedence when working with `Any`

- .github/workflows/test.yml
- SwiftCBOR.xcodeproj/project.pbxproj
Sets the dylib compatibility versions used in build to match those generated by a Pods build. Currently a binary framework that depends on this framework cannot use an output built by a Carthage build if the downstream framework was built by Pods, as the dylib version specifications aren't compatible.
> Specify dylib compatibility version

- SwiftCBOR.xcodeproj/project.pbxproj
When using the Carthage build we get a warning that the Framework wasn't built for use in app extensions. PR just sets a flag in project to mark it as safe for use in extensions to get rid of this warning.
> Allow for use in app extensions

- SwiftCBOR.xcodeproj/project.pbxproj
We ran into an issue on MacOS 10.3 where SwiftCBOR was trying to load incompatible Swift libraries from an old version of Xcode. It seems this is because the RPATH contains hardcoded links to Xcode added by Swift Package Manager for this module. See https://developer.apple.com/forums/thread/115551
This PR removes the Xcode specific RPATH entry for SwiftCBOR binaries.
> Remove Xcode path from LD_RUNPATH_SEARCH_PATHS

- Sources/SwiftCBOR/Decoder/CodableCBORDecoder.swift
- Sources/SwiftCBOR/Decoder/KeyedDecodingContainer.swift
- Sources/SwiftCBOR/Decoder/SingleValueDecodingContainer.swift
- Sources/SwiftCBOR/Decoder/UnkeyedDecodingContainer.swift
Another massive performance improvement for decoding. The decoder and decoding containers previously used to constantly create new Data objects while parsing the payload (suffix in combination with map) leading to hundreds of thousands recreated data structures even while parsing a small payload. This change massively improves the performance by completely switching to ArraySlice for the individual bytes instead of recreating objects.
The attached images show the before and after for test cases we have written which parse the data from the Acceptance System of the Austrian Gateway for EU Digital COVID Certificates (See https://github.com/Federal-Ministry-of-Health-AT/green-pass-overview for the endpoints about trustlist, business rules and value sets) which improves the parsing speed by a …
> Massive performance improvements by switching from using Data to ArraySlice

- .github/workflows/test.yml
- Sources/SwiftCBOR/Decoder/KeyedDecodingContainer.swift
- Tests/SwiftCBORTests/CBORCodableRoundtripTests.swift
The test that has been added as part of this PR was failing with the code currently on `master` but now passes with the rest of changes in this PR.
The fix is far from ideal because we should be able to use the container as is from `self.nestedContainers` but because when this function is called:
```swift
func nestedContainer<NestedKey: CodingKey>(
keyedBy type: NestedKey.Type,
forKey key: Key
) throws -> KeyedDecodingContainer<NestedKey> {
```
the `NestedKey` type is actually typed as `Order.Status.DoneCodingKeys` (i.e. the auto-generated `CodingKey`-related type for the `done` case of the `Status` enum). 
The casting of `self.nestedContainers[AnyCodingKey(key)]` to `_CBORDecoder.KeyedContainer<NestedKey>` always then fails because containers were previously inserted into …
> Fix the decoding of `Codable` enums

- .github/workflows/test.yml
- Sources/SwiftCBOR/AnyCodingKey.swift
- Sources/SwiftCBOR/CBOREncodable.swift
- Sources/SwiftCBOR/CBOREncoder.swift
- Sources/SwiftCBOR/CBOROptions.swift
- Sources/SwiftCBOR/Decoder/CodableCBORDecoder.swift
- Sources/SwiftCBOR/Decoder/KeyedDecodingContainer.swift
- Sources/SwiftCBOR/Decoder/SingleValueDecodingContainer.swift
- Sources/SwiftCBOR/Decoder/UnkeyedDecodingContainer.swift
- Sources/SwiftCBOR/Encoder/CodableCBOREncoder.swift
- Sources/SwiftCBOR/Encoder/KeyedEncodingContainer.swift
- Sources/SwiftCBOR/Encoder/SingleValueEncodingContainer.swift
- Sources/SwiftCBOR/Encoder/UnkeyedEncodingContainer.swift
- SwiftCBOR.xcodeproj/project.pbxproj
- Tests/SwiftCBORTests/CBORCodableRoundtripTests.swift
- Tests/SwiftCBORTests/CBOREncoderTests.swift
Fixes `CodableCBORDecoder` decoding of lots of different types, particularly ones that get encoded to unkeyed or keyed containers, as well as `Date`s that were getting encoded as a tagged value but were not being handled in the decode path.
Also introduces `CBOROptions` (and other related `Options`-based types) to allow users to specify options relating to how they want the CBOR to be encoded. This is currently only really relevant when dealing with `Codable`-conforming types that have `CodingKeys` that can be encoded as strings or integers. Lots of types in `Foundation` happen to such types. For some use cases it can be desirable to be able to control whether the keys in these maps get encoded as strings or integers.
> `Codable`-related fixes

- Sources/SwiftCBOR/CBOREncoder.swift
- Sources/SwiftCBOR/CBOROptions.swift
- Sources/SwiftCBOR/Encoder/CodableCBOREncoder.swift
- Tests/SwiftCBORTests/CBORCodableRoundtripTests.swift
- Tests/SwiftCBORTests/CBOREncoderTests.swift
The current encoding APIs are generally non-throwing and so in a lot of places
we'd end up with a change to a throwing API if the various `encodeMap`
implementations were turned into throwing functions (some of them already are
though).
For now I've decided to leave this as are and use a `try!` in the cases where
the current `encodeMap` implementation is non-throwing. This will therefore lead
to runtime errors but I think this is fine for now given that the option to
forbid non-String map keys is opt-in.
It might be useful in the future to either change most/all of the
`encode`-relevant functions to be throwing. Either that or perhaps there could
be throwing versions to live alongside the non-throwing versions that currently
exist.
> Add an option to forbid non-String map keys.

- Sources/Decoder/CodableCBORDecoder.swift
- Sources/Decoder/KeyedDecodingContainer.swift
- Sources/Decoder/SingleValueDecodingContainer.swift
- Sources/Decoder/UnkeyedDecodingContainer.swift
- Tests/CBORCodableRoundtripTests.swift
- Tests/CBORDecoderTests.swift
- Tests/Helpers.swift
See the individual commits for more information about each fix.
> Fixes for: empty optional array, trying to decode mismatched types doesn't error, and `Codable` decoding of indefinites maps/arrays

- Sources/CBOREncodable.swift
- Sources/CBOREncoder.swift
- Tests/CBOREncodableTests.swift
- Tests/CBOREncoderTests.swift
Update the `CBOREncodable` protocol to require that a `toCBOR` function be
implemented. The `encode` function can then rely on a default implementation
that will call `toCBOR()` and then encode the resulting `CBOR` object.
> Update the `CBOREncodable` protocol to require a `toCBOR` function

- Sources/Decoder/UnkeyedDecodingContainer.swift
- Tests/CBORCodableRoundtripTests.swift
> Fix bug when decoding struct containing optional array of `Codable`-conforming struct

- Sources/CBORDecoder.swift
- Sources/CBOROptions.swift
- Sources/Decoder/CodableCBORDecoder.swift
- Tests/CBORDecoderTests.swift
Added the ability to specify a maximum depth for CBOR decoding. This addresses a crash reported in #92 that can occur when certain types of data causes the recursive nature of the decoder to escape the stack for the given thread. I do suggest we set a more reasonable default than `.max`, though that can break some user's workflows if they weren't expecting it, so maybe requires a new version? Food for thought 😅
> Added the ability to specify a maximum depth for CBOR decoding

- Sources/CBOR.swift
Fix data racing error for Swift 6
```
Static property 'standardDateTimeString' is not concurrency-safe because non-'Sendable' type 'CBOR.Tag' may have shared mutable state
```
> Fix Sendable error in Swift 6

- Sources/CBOREncodable.swift
- Tests/CBOREncoderTests.swift
Fixes https://github.com/valpackett/SwiftCBOR/issues/98
> Use `encodeVarUint()` method again for `UInt`

- Sources/CBOR.swift
`NSEC_PER_SEC` cannot be found on Windows
> Fix building for Windows

- .github/workflows/test.yml
- Package.swift
This adds support for Mac Catalyst as a deployment target (for SPM, I couldn't find the appropriate `.podspec` syntax, if one exists).
I have confirmed that this works on my Mac. The unit tests pass, and it builds & works properly when integrated into another app that supports Mac Catalyst as a deployment target.
> Adds SPM support for Mac Catalyst

- .github/workflows/test.yml
- Sources/CBOR.swift
- Tests/CBORDecoderTests.swift
This fix makes the one tweak needed to build on Android, as well as adding CI for Android (using [swift-android-action](https://github.com/marketplace/actions/swift-android-action)) to ensure that it continues to work.
> Android support and CI
